#!/bin/bash
cd searchit
display_help(){
    echo -e "browse [webpage] [search]\n"\
            "**********************************************************\n"\
            "Description:\n"\
            "Use the given website search function without opening the page.\n"\
            "**********************************************************\n"\
            "List of all availabe commands:\n\n"\
            "browse [webpage] [search]\tWill search a website with [search]\n"\
            "-f [\"search link\"]\tUsed for unscrapable websites by searching test and using the given link in quotes\n"\
            "-l\tLists all saved websites"
}

stored_exists(){
    if [[ -f stored.txt ]]; then
        if [[ -n $(grep $1 stored.txt) ]]; then
            return 0
        fi
    fi
    return 1
}

case $1 in
    --help)
        display_help
        ;;
    -f)
        if [[ -n $2 ]]; then
            python searchit.py find $2
        else
            echo "Please enter a url returned from a website when searching 'test'."
        fi
        ;;
    -l)
        if [[ -f stored.txt ]];then
            echo "This is a list of saved websites:"
            cut -d" " -f1 stored.txt
        else
            echo "No stored websites."
        fi
        ;;
    *)
        if [[ $# == 2 && $(stored_exists $1) || $1 =~ [a-zA-Z0-9@:%._\+~#=]+\.[a-zA-Z]+ ]]; then
            python searchit.py $@
        else
            echo "You entered something wrong."
            display_help
        fi
        ;;
esac
